### ISSUE TITLE
ModuleNotFoundError: No module named 'server'

### ISSUE THREAD

**Issue by mr7r25** [sadjadeb/qrCode_ticket#1]
I just cloned the project and used following command to run the server :

`python main.py run_webserver`

but I got the following error:
```
    from server.config import *
ModuleNotFoundError: No module named 'server'
```

How can I fix that?

**Comment by Afshari9978** [comment]
You should remove `server.` from first 2 lines of `webserver.py` file. 

- Then you might encounter with `RuntimeError: Directory 'client/static' does not exist` error, which means you should change `"client/static"` on line 7 to `"../client/static"`.
- If you don't have `INPUT_FILE_PATH` & `OUTPUT_FILE_PATH` files prepared, server won't run. You can simply create two excel files with columns "first_name", "last_name", "phone_number" and "ticket_id" for `INPUT_FILE_PATH` and an empty excel file for `OUTPUT_FILE_PATH`.

**Comment by sadjadeb** [comment]
Thanks for your attention. This issue has been resolved.
